[package]
name = "rust_evm"
version = "0.1.0"
edition = "2021"
members = [
    "vm",
    "eth"
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
vm = { path = "./vm" }
eth = { path = "./eth" }
